version: '3.9'
services:

  mysql:
    container_name: mysql
    image: mysql:8.0.31
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: keycloak
    ports:
      - 3316:3306
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    command: --lower_case_table_names=1
    restart: unless-stopped

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:20.0.1
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: mysql
      KC_DB_SCHEMA: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_DB_URL: jdbc:mysql://mysql/keycloak
    ports:
      - 8080:8080
    volumes:
      - ./init/betting-app-realm.json:/opt/keycloak/data/import/betting-app-realm.json
    depends_on:
      - mysql
    command: [ "start-dev", "--import-realm" ]
    restart: unless-stopped

  discovery-server:
    image: dearmann/discovery-server:1.0
    container_name: discovery-server
    ports:
      - 8761:8761
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    restart: unless-stopped

  api-gateway:
    image: dearmann/api-gateway:1.0
    container_name: api-gateway
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY=TRACE
    depends_on:
      - discovery-server
      - keycloak
    restart: unless-stopped

  match-service:
    container_name: match-service
    image: dearmann/match-service:1.1
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
    depends_on:
      - mysql
    restart: unless-stopped

  user-service:
    container_name: user-service
    image: dearmann/user-service:1.0
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - KEYCLOAK_URL=http://keycloak:8080
      - KEYCLOAK_REALM=betting-app
      - KEYCLOAK_CLIENT_ID=backend
      - KEYCLOAK_SECRET=xDexo0gzAq3DP6wDt6f96WpMvBAZJzVB
      - KEYCLOAK_USERNAME=admin
      - KEYCLOAK_PASSWORD=admin
    depends_on:
      - mysql
      - discovery-server
      - api-gateway
    restart: unless-stopped

  bet-service:
    container_name: bet-service
    image: dearmann/bet-service:1.0
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - mysql
      - discovery-server
      - api-gateway
    restart: unless-stopped

  comment-service:
    container_name: comment-service
    image: dearmann/comment-service:1.0
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - mysql
      - discovery-server
      - api-gateway
    restart: unless-stopped

  rate-service:
    container_name: rate-service
    image: dearmann/rate-service:1.0
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - mysql
      - discovery-server
      - api-gateway
    restart: unless-stopped

  frontend:
    container_name: betting-app-ui
    image: dearmann/betting-app-ui:1.1
    ports:
      - 80:80
    environment: 
      - KEYCLOAK_URL=http://keycloak:8080
      - KEYCLOAK_REALM=betting-app
      - KEYCLOAK_CLIENT_ID=frontend
      - BACKEND_BASE_PATH=http://api-gateway:8080
    depends_on:
      - keycloak
      - api-gateway
    restart: unless-stopped

volumes:
  mysql-data: