server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: discovery-server
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/
        - id: discovery-server-static-resources
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/**
        - id: bet-service
          uri: lb://bet-service
          predicates:
            - Path=/bets/**
        - id: comment-service
          uri: lb://comment-service
          predicates:
            - Path=/comments/**
        - id: rate-service
          uri: lb://rate-service
          predicates:
            - Path=/ratings/**
        - id: match-service
          uri: lb://match-service
          predicates:
            - Path=/games/**,/events/**,/teams/**,/matches/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**,/keycloak/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200/"
            allowedHeaders: "*"
            allowedMethods:
              - POST
              - GET
              - PUT
              - DELETE
              - OPTIONS
              - HEAD
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${KEYCLOAK_SERVICE:localhost:8181}/realms/betting-app

logging:
  level:
    root: INFO
    org:
      springframework:
        cloud:
          gateway: TRACE
          gateway.route.RouteDefinitionRouteLocator: INFO