apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret
type: Opaque
data:
  keycloak-user: YWRtaW4=
  keycloak-password: YWRtaW4=
  keycloak-admin: YWRtaW4=
  keycloak-admin-password: YWRtaW4=
