apiVersion: apps/v1
kind: Deployment
metadata:
  name: comment-service
  labels:
    app: comment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: comment-service
  template:
    metadata:
      labels:
        app: comment-service
    spec:
      containers:
        - name: comment-service
          image: dearmann/comment-service:1.2
          ports:
            - containerPort: 8083
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: mysql-configmap
                  key: mysql-hostname
            - name: DB_NAME
              value: commentdb
            - name: DB_USERNAME
              value: comment
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-service-password
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: comment-service
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8083
  selector:
    app: comment-service
