apiVersion: apps/v1
kind: Deployment
metadata:
  name: bet-service
  labels:
    app: bet-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bet-service
  template:
    metadata:
      labels:
        app: bet-service
    spec:
      containers:
        - name: bet-service
          image: dearmann/bet-service:1.1
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: bet-service
  labels:
    app: bet-service
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
      nodePort: 30005
  selector:
    app: bet-service
