apiVersion: apps/v1
kind: Deployment
metadata:
  name: match-service
  labels:
    app: match-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: match-service
  template:
    metadata:
      labels:
        app: match-service
    spec:
      containers:
        - name: match-service
          image: dearmann/match-service:1.3
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: mysql-configmap
                  key: mysql-hostname
            - name: DB_NAME
              value: matchdb
            - name: DB_USERNAME
              value: match
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-service-password
            - name: AWS_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: aws-access-key
            - name: AWS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: aws-secret-key
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: match-service
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
  selector:
    app: match-service
